theme: jekyll-theme-minimal
title: JinyangLI
github:
  is_project_page: false
logo: "/LI.jpg?raw=true"
description: >
  Core Z <br>
  PolyU KLN Hong Kong<br>
  Email: <a href="http://bradlisy@gmail.com"> bradlisy@gmail.com <br><br>
  <a href="https://www.linkedin.com/in/amirali-najafi-3894ab1b4/"> View My LinkedIn Profile</a>
  <br>
  <a href="https://scholar.google.com/citations?hl=en&user=kGZwM9QAAAAJ"> View My Google Scholar Profile</a>
