theme: jekyll-theme-minimal
title: JinyangLI
github:
  is_project_page: false
logo: "/amirali.jpg?raw=true"
description: >
  205 N. Mathews Ave. Urbana IL<br>
  1141 Nathan Newmark Building<br>
  Email: anajafi2@illinois.edu <br><br>
  <a href="https://www.linkedin.com/in/amirali-najafi-3894ab1b4/"> View My LinkedIn Profile</a>
  <br>
  <a href="https://scholar.google.com/citations?hl=en&user=kGZwM9QAAAAJ"> View My Google Scholar Profile</a>

