theme: jekyll-theme-minimal
title: LI, Jin-Yang
github:
  is_project_page: false
logo: "/JYL.jpg?raw=true"
description: >
  PolyU KLN Hong Kong<br>
  RM 910 Core Z <br>
  Email: <a href="http://bradlisy@gmail.com"> bradlisy at gmail dot com</a>
  <br>
  <a href="https://scholar.google.com.hk/citations?user=jNNMpKUAAAAJ&hl=en"> View My Google Scholar Profile</a>
